name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.5.0
homepage: https://github.com/Groseuros/eosdart-1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0
  pointycastle: ^3.3.4
  eosdart_ecc: ^0.4.4
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
